version: '3.0'
services:
  umpire:
    build: ./docker/umpire
    hostname: umpire
    stdin_open: true
  team1:
    build: ./docker/team_server
    hostname: team1
    stdin_open: true
    ports:
      - "2221:22"
  team2:
    build: ./docker/team_server
    hostname: team2
    stdin_open: true
    ports:
      - "2222:22"

# Need to create an ssh key for the umpire to be able to scp to the team containers